//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToUs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassManagers = new HashSet<ClassManager>();
        }
    
        public long Id { get; set; }
        public string ClassId { get; set; }
        public Nullable<int> NumberOfStudents { get; set; }
        public string Room { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string System { get; set; }
        public string Language { get; set; }
        public string DayInWeek { get; set; }
        public string Lession { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Semester { get; set; }
        public int Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassManager> ClassManagers { get; set; }
    }
}
