//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToUs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectBackUp
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfDigits { get; set; }
        public string HTGD { get; set; }
        public string FacultyId { get; set; }
        public Nullable<bool> IsLab { get; set; }
        public int Year { get; set; }
        public int Semester { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
